/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* INSTAGRAM IMAGE LIST */
export const INSTAGRAM_IMAGE_LIST = 'INSTAGRAM_IMAGE_LIST';
export const INSTAGRAM_IMAGE_LIST_SUCCESS = 'INSTAGRAM_IMAGE_LIST_SUCCESS';
export const INSTAGRAM_IMAGE_STATUS_CHANGE = 'INSTAGRAM_IMAGE_STATUS_CHANGE';
export const INSTAGRAM_IMAGE_STATUS_CHANGE_SUCCESS = 'INSTAGRAM_IMAGE_STATUS_CHANGE_SUCCESS';

/* WIDGET LIST */
export const WIDGET_LIST = 'WIDGET_LIST';
export const WIDGET_LIST_SUCCESS = 'WIDGET_LIST_SUCCESS';
export const WIDGET_ADD = "WIDGET_ADD";
export const WIDGET_ADD_SUCCESS = "WIDGET_ADD_SUCCESS";
export const WIDGET_GET = "WIDGET_GET";
export const WIDGET_GET_SUCCESS = "WIDGET_GET_SUCCESS";
export const WIDGET_UPDATE = "WIDGET_UPDATE";
export const WIDGET_UPDATE_SUCCESS = "WIDGET_UPDATE_SUCCESS";
